name: NPM Publish

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
  
      - name: Build & Set Package Version to Tag
        run: |
          bun install --frozen-lockfile
          bun run build
          VERSION=${GITHUB_REF#refs/tags/}
          npm version $VERSION --no-git-tag-version
      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
